# Numpy高级应用

## ndarray对象的内部机理

ndarray内部由一下内容组成：
- 一个指向数组的指针
- dtype
- shape
- stride

In [2]:
import numpy as np

### NumPy数据类型体系

In [3]:
# 检查数组中包含数据的类型：np.issubdtype
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)

In [4]:
np.issubdtype(ints.dtype, np.integer)

True

In [5]:
np.issubdtype(floats.dtype, np.floating)

True

In [6]:
# 调用dtype的mro方法即可查看其所有父类
# MRO(Method Resolution Order，方法解顺序)
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

## 高级数组操作
除了花式索引、切片、布尔条件取子集等操作外，数组操作还有很多。
除了pandas提供的，有时还需要自己编写一些找不到的**数据算法**。

### 数组重塑

In [7]:
arr = np.arange(8).reshape((4, 2))
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [8]:
# 作为参数的形状的其中一维可以是-1
# 表示该维度大小由数据本身推断而来
arr = np.arange(15).reshape((5, -1))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [9]:
# 将多维数组转换为一维数组的运算通常称为扁平化（flattening）或者散开（raveling）
arr = np.arange(15).reshape((5, 3)).ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr = np.arange(15).reshape((5, 3)).flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### C和Fortran的顺序

In [11]:
# C：行优先书序；Fortran：列优先顺序
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
# 默认为C顺序
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
# Fortran
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### 数组的合并和拆分

In [14]:
# numpy.concatenate可以按指定轴将两个ndarray链接到一起
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [16]:
# 等价的，可以用vstack和hstack实现
# vertical stack & horizonal stack
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [18]:
from numpy.random import randn

In [19]:
# 相反，split用于将一个数组沿指定轴拆分为多个数组
arr = randn(5, 2)
first, second, third = np.split(arr, [1, 3])
print(first)
print(second)
print(third)

[[ 0.90431183 -0.92949191]]
[[0.41513351 0.0413852 ]
 [1.57425829 0.33579042]]
[[ 0.14917699  0.0121404 ]
 [-0.58468371  0.78169745]]


In [20]:
arr

array([[ 0.90431183, -0.92949191],
       [ 0.41513351,  0.0413852 ],
       [ 1.57425829,  0.33579042],
       [ 0.14917699,  0.0121404 ],
       [-0.58468371,  0.78169745]])

In [21]:
# 堆叠辅助类
# numpy中有两个特殊的命名对象r_和c_（分别对应行优先合并和列优先合并）
arr1 = np.arange(6).reshape((3, 2))
arr2 = randn(3, 2)

In [22]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 0.89181725, -0.96089163],
       [-0.76307005,  2.15397254],
       [-0.36473053,  0.60320703]])

In [24]:
np.c_[np.r_[arr1, arr2], arr1.ravel()]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 0.89181725, -0.96089163,  3.        ],
       [-0.76307005,  2.15397254,  4.        ],
       [-0.36473053,  0.60320703,  5.        ]])

In [25]:
# 还可以打印切片
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])